# Generated by Django 3.1.2 on 2020-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheeseQuery', '0002_auto_20201010_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='quality',
            field=models.IntegerField(default=5),
        ),
    ]
