# Generated by Django 3.1.2 on 2020-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
