# Generated by Django 3.1.2 on 2020-10-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Employee',
        ),
    ]
