# Generated by Django 3.1.2 on 2020-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Columbus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
