# Generated by Django 3.1.2 on 2020-10-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
