# Generated by Django 3.1.2 on 2020-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Query', '0004_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
    ]
