# Generated by Django 3.1.2 on 2020-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ram_size', models.PositiveIntegerField(default=0)),
                ('type_of', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
