# Generated by Django 3.1.2 on 2020-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apnumber', models.IntegerField()),
                ('intcomma', models.IntegerField()),
                ('intword', models.IntegerField()),
                ('naturalday', models.DateField()),
                ('naturaltime', models.DateTimeField()),
                ('ordinal', models.IntegerField()),
            ],
        ),
    ]
